POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmluYTciLCJpZCI6IjVlOWE5OGFmN2JkZTdiMzcxNGI2Yjg5NyIsImlhdCI6MTU4ODU2OTE3M30.Fa1xygRLr-wJqqkyrQMMIixYsGrOUW_-NNCz4JZXOIQ

{
    "title":"my6 blog",
    "author":"Leena",
    "url":"http://leenablog.com",
    "likes": 10
}